# Generated by Django 3.0.8 on 2020-07-31 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adquirente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adquirente', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=10)),
                ('nome', models.CharField(max_length=80)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('cidade', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Modelomaquininha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'verbose_name': 'Modelo Maquininha',
                'verbose_name_plural': 'Modelos Maquininhas',
            },
        ),
        migrations.CreateModel(
            name='Maquininha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_logico', models.CharField(max_length=40, unique=True)),
                ('terminal', models.CharField(max_length=40, unique=True)),
                ('data_ativacao', models.DateField()),
                ('os_ativacao', models.CharField(max_length=30)),
                ('data_inativacao', models.DateField(blank=True, default=None, null=True)),
                ('os_inativacao', models.CharField(blank=True, max_length=30, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('adquirente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LOG_WEB.Adquirente')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LOG_WEB.Estabelecimento')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LOG_WEB.Modelomaquininha')),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=10)),
                ('nome', models.CharField(max_length=100)),
                ('funcao', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('observacao', models.TextField(blank=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LOG_WEB.Estabelecimento')),
            ],
            options={
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['nome'],
            },
        ),
    ]
