# Generated by Django 3.0.8 on 2020-07-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOG_WEB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='nome',
            field=models.CharField(max_length=80),
        ),
    ]
