# Generated by Django 3.0.8 on 2020-07-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOG_WEB', '0002_auto_20200729_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='status',
            field=models.CharField(choices=[('Ativo', 'ativo'), ('Inativo', 'inativo')], default='Ativo', max_length=10),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='cpf',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='observacao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
