# Generated by Django 3.0.8 on 2020-07-29 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LOG_WEB', '0003_auto_20200729_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=10)),
                ('nome', models.CharField(max_length=80)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('cidade', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='motorista',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=10),
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=10)),
                ('nome', models.CharField(max_length=100)),
                ('funcao', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('observacao', models.TextField(blank=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LOG_WEB.Estabelecimento')),
            ],
        ),
    ]
